### ISSUE TITLE
sm is taken

### ISSUE THREAD

**Issue by anordal** [xyproto/cxx#1]
Nice name, but the `sm` command on OpenSuse and Ubuntu refers to [screen-message](https://github.com/nomeata/screen-message).

**Comment by xyproto** [comment]
Oh no, will have to find a new short name for the next version. Thanks!

**Comment by xyproto** [comment]
I'm planning to rewrite Sakemake in the future, so that it no longer depends on Make and SCons. Will find a new and better name then.

**Comment by xyproto** [comment]
Renamed to cxx.
