### ISSUE TITLE
windows port?

### ISSUE THREAD

**Issue by Ryder17z** [xyproto/cxx#4]

**Comment by xyproto** [comment]
Thank you for the question. Not at the current time.

I am planning on rewriting cxx in Go, Zig or Rust in the future, though. When/if that time comes, I will also look into adding Windows support. `cxx` currently supports building .exe files for Windows, but does not run on Windows right now, as far as I am aware.

**Comment by ExileFox** [comment]
Alright, thanks for the quick reply.

**Comment by ExileFox** [comment]
I have played around a little bit with Zig and I like it, so I would be interested in a zig port in the future if you decide to do so.

**Comment by xyproto** [comment]
Zig is still a possibility. If we just wait a year, I assume LLMs will be good enough to just port it automatically to both Rust and Zig, though.
